# Note: Fasd development has stopped, so the last version is hardcoded here.
---
- name: Check if fasd already installed
  shell: command -v fasd
  register: fasd_installed
  ignore_errors: yes
  changed_when: false
  failed_when: false
  tags: fasd

- block:
  - name: create /tmp/fasd
    file:
      path: /tmp/fasd
      state: directory

  - name: extract fasd to /tmp/
    become: yes
    unarchive:
      src: "https://github.com/clvv/fasd/archive/1.0.1.tar.gz"
      dest: /tmp/fasd
      copy: no
      list_files: no
      extra_opts: "--strip-components=1"
      creates: "/tmp/fasd/fasd"

  - name: install fasd
    command: make install
    args:
      chdir: "/tmp/fasd"
      creates: "/usr/local/bin/fasd"
    become: yes

  when: fasd_installed.rc != 0
  tags:
    - fasd
